version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: "medidb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "senha123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  api:
    build:
      context: .  # Diretório onde está o Dockerfile e o código fonte da API
      dockerfile: Dockerfile  # Nome do Dockerfile
    container_name: my-api-container
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5231:8080"  # Mapeia a porta 8080 do container para a porta 5231 no host
    depends_on:
      - postgres
